# Generated by Django 6.0.1 on 2026-01-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendario',
            new_name='Agendamento',
        ),
    ]
